# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = false

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 24

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 8
inner.vertical =   8
outer.left =       4
outer.bottom =     4
outer.top =        4
outer.right =      4

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
################################################################################
[mode.main.binding]

cmd-ctrl-shift-alt-space = 'mode leader'
cmd-ctrl-shift-alt-w = 'mode workspace'
cmd-ctrl-shift-alt-semicolon = 'mode workspace'

cmd-ctrl-shift-alt-h = 'focus left'
cmd-ctrl-shift-alt-j = 'focus down'
cmd-ctrl-shift-alt-k = 'focus up'
cmd-ctrl-shift-alt-l = 'focus right'

cmd-ctrl-shift-alt-z = 'focus left'
cmd-ctrl-shift-alt-x = 'focus down'
cmd-ctrl-shift-alt-c = 'focus up'
cmd-ctrl-shift-alt-v = 'focus right'

cmd-ctrl-shift-alt-a = 'workspace A'
cmd-ctrl-shift-alt-s = 'workspace S'
cmd-ctrl-shift-alt-d = 'workspace D'
cmd-ctrl-shift-alt-f = 'workspace F'


################################################################################
[mode.leader.binding]

esc = 'mode main'
w = 'mode workspace'

shift-f = ['flatten-workspace-tree', 'mode main'] # reset layout
b = ['balance-sizes', 'mode main']
shift-r = ['reload-config', 'mode main']

minus = 'resize smart -50' 
shift-minus = 'resize smart -300'
equal = 'resize smart +50'
shift-equal = 'resize smart +300'

h = 'move left'
shift-h = ['move left', 'mode main']
j = 'move down'
shift-j = ['move down', 'mode main']
k = 'move up'
shift-k = ['move up', 'mode main']
l = 'move right'
shift-l = ['move right', 'mode main']

y = ['join-with left', 'layout accordion horizontal vertical', 'mode main']
u = ['join-with down', 'layout accordion horizontal vertical', 'mode main']
i = ['join-with up', 'layout accordion horizontal vertical', 'mode main']
o = ['join-with right', 'layout accordion horizontal vertical', 'mode main']

cmd-ctrl-shift-alt-h = 'join-with left'
cmd-ctrl-shift-alt-j = 'join-with down'
cmd-ctrl-shift-alt-k = 'join-with up'
cmd-ctrl-shift-alt-l = 'join-with right'

t = 'layout tiles horizontal vertical'
shift-t = ['layout tiles horizontal vertical', 'mode main']
a = 'layout accordion horizontal vertical'
shift-a = ['layout accordion horizontal vertical', 'mode main']
f = 'layout floating tiling'



################################################################################
[mode.workspace.binding]

esc = 'mode main'

a = ['move-node-to-workspace A', 'mode main']
s = ['move-node-to-workspace S', 'mode main']
d = ['move-node-to-workspace D', 'mode main']
f = ['move-node-to-workspace F', 'mode main']






### BEGIN DEFAULTS ############################################################
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
# cmd-ctrl-shift-alt-slash = 'layout tiles horizontal vertical'
# cmd-ctrl-shift-alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
# cmd-ctrl-shift-alt-h = 'focus left'
# cmd-ctrl-shift-alt-j = 'focus down'
# cmd-ctrl-shift-alt-k = 'focus up'
# cmd-ctrl-shift-alt-l = 'focus right'

# # See: https://nikitabobko.github.io/AeroSpace/commands#move
# alt-h = 'move left'
# alt-j = 'move down'
# alt-k = 'move up'
# alt-l = 'move right'

# # See: https://nikitabobko.github.io/AeroSpace/commands#resize
# alt-shift-minus = 'resize smart -50'
# alt-shift-equal = 'resize smart +50'


# # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
# cmd-ctrl-shift-alt-1 = 'workspace 1'
# cmd-ctrl-shift-alt-2 = 'workspace 2'
# cmd-ctrl-shift-alt-3 = 'workspace 3'
# cmd-ctrl-shift-alt-4 = 'workspace 4'
# cmd-ctrl-shift-alt-5 = 'workspace 5'
# cmd-ctrl-shift-alt-6 = 'workspace 6'
# cmd-ctrl-shift-alt-7 = 'workspace 7'
# cmd-ctrl-shift-alt-8 = 'workspace 8'
# cmd-ctrl-shift-alt-9 = 'workspace 9'
# cmd-ctrl-shift-alt-a = 'workspace A' # In your config, you can drop workspace bindings that you don't need
# cmd-ctrl-shift-alt-b = 'workspace B'
# cmd-ctrl-shift-alt-c = 'workspace C'
# cmd-ctrl-shift-alt-d = 'workspace D'
# cmd-ctrl-shift-alt-e = 'workspace E'
# cmd-ctrl-shift-alt-f = 'workspace F'
# cmd-ctrl-shift-alt-g = 'workspace G'
# cmd-ctrl-shift-alt-i = 'workspace I'
# cmd-ctrl-shift-alt-m = 'workspace M'
# cmd-ctrl-shift-alt-n = 'workspace N'
# cmd-ctrl-shift-alt-o = 'workspace O'
# cmd-ctrl-shift-alt-p = 'workspace P'
# cmd-ctrl-shift-alt-q = 'workspace Q'
# cmd-ctrl-shift-alt-r = 'workspace R'
# cmd-ctrl-shift-alt-s = 'workspace S'
# cmd-ctrl-shift-alt-t = 'workspace T'
# cmd-ctrl-shift-alt-u = 'workspace U'
# cmd-ctrl-shift-alt-v = 'workspace V'
# cmd-ctrl-shift-alt-w = 'workspace W'
# cmd-ctrl-shift-alt-x = 'workspace X'
# cmd-ctrl-shift-alt-y = 'workspace Y'
# cmd-ctrl-shift-alt-z = 'workspace Z'

# # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
# alt-1 = 'move-node-to-workspace 1'
# alt-2 = 'move-node-to-workspace 2'
# alt-3 = 'move-node-to-workspace 3'
# alt-4 = 'move-node-to-workspace 4'
# alt-5 = 'move-node-to-workspace 5'
# alt-6 = 'move-node-to-workspace 6'
# alt-7 = 'move-node-to-workspace 7'
# alt-8 = 'move-node-to-workspace 8'
# alt-9 = 'move-node-to-workspace 9'
# alt-a = 'move-node-to-workspace A'
# alt-b = 'move-node-to-workspace B'
# alt-c = 'move-node-to-workspace C'
# alt-d = 'move-node-to-workspace D'
# alt-e = 'move-node-to-workspace E'
# alt-f = 'move-node-to-workspace F'
# alt-g = 'move-node-to-workspace G'
# alt-i = 'move-node-to-workspace I'
# alt-m = 'move-node-to-workspace M'
# alt-n = 'move-node-to-workspace N'
# alt-o = 'move-node-to-workspace O'
# alt-p = 'move-node-to-workspace P'
# alt-q = 'move-node-to-workspace Q'
# alt-r = 'move-node-to-workspace R'
# alt-s = 'move-node-to-workspace S'
# alt-t = 'move-node-to-workspace T'
# alt-u = 'move-node-to-workspace U'
# alt-v = 'move-node-to-workspace V'
# alt-w = 'move-node-to-workspace W'
# alt-x = 'move-node-to-workspace X'
# alt-y = 'move-node-to-workspace Y'
# alt-z = 'move-node-to-workspace Z'

# # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
# alt-tab = 'workspace-back-and-forth'

# # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
# alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# # See: https://nikitabobko.github.io/AeroSpace/commands#mode
# alt-shift-semicolon = 'mode service'

# # 'service' binding mode declaration.
# # See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# [mode.service.binding]
# esc = ['reload-config', 'mode main']
# r = ['flatten-workspace-tree', 'mode main'] # reset layout
# f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
# backspace = ['close-all-windows-but-current', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

# alt-shift-h = ['join-with left', 'mode main']
# alt-shift-j = ['join-with down', 'mode main']
# alt-shift-k = ['join-with up', 'mode main']
# alt-shift-l = ['join-with right', 'mode main']

# down = 'volume down'
# up = 'volume up'
# shift-down = ['volume set 0', 'mode main']
